_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 3
DATASETS:
  TRAIN: ("kitti_train",)
SOLVER:
  STEPS: (350000, 420000)
  MAX_ITER: 450000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  FORMAT: "BGR"
VIEWPOINT: True
ROTATED_BOX_TRAINING: True
HEIGHT_TRAINING: True
VIEWPOINT_RESIDUAL: True
VP_BINS: 12
